# Generated by Django 4.2.5 on 2023-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_prodotto_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='descrizione',
            field=models.TextField(default='Descrizione di default'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='nome',
            field=models.TextField(default='Nome di default'),
        ),
    ]
