# Generated by Django 4.2.5 on 2023-10-13 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0004_carrello_elementocarrello'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodotto',
            name='categoria',
            field=models.TextField(default='default', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrello',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='descrizione',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='nome',
            field=models.TextField(max_length=250),
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=150)),
                ('cognome', models.TextField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('numero_telefono', models.TextField(max_length=20)),
                ('indirizzo', models.TextField(max_length=254)),
                ('citta', models.TextField(max_length=150)),
                ('regione', models.TextField(max_length=150)),
                ('provincia', models.TextField(max_length=150)),
                ('codice_postale', models.TextField(max_length=10)),
                ('prezzo_totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modalita_pagamento', models.TextField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
