# Generated by Django 4.2.5 on 2023-10-14 10:36

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_prodotto_categoria_alter_carrello_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='numero_telefono',
        ),
        migrations.AddField(
            model_name='ordine',
            name='stato',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
