# Generated by Django 4.2.5 on 2023-10-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_ordine_numero_telefono_ordine_stato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='prezzo_totale',
        ),
        migrations.AddField(
            model_name='ordine',
            name='prodotti',
            field=models.ManyToManyField(to='polls.prodotto'),
        ),
    ]
