# Generated by Django 4.2.5 on 2023-10-20 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_remove_ordine_prezzo_totale_ordine_prodotti'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(max_length=250)),
                ('descrizione', models.TextField(max_length=400)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.TextField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='modalita_pagamento',
        ),
        migrations.RemoveField(
            model_name='ordine',
            name='prodotti',
        ),
        migrations.AlterField(
            model_name='ordine',
            name='stato',
            field=models.TextField(max_length=254),
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_carta', models.TextField()),
                ('numero_carta', models.IntegerField()),
                ('scadenza', models.DateField()),
                ('cvv', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordine',
            name='elemento_ordine',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='polls.elementoordine'),
        ),
        migrations.AddField(
            model_name='ordine',
            name='pagamento',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.pagamento'),
        ),
    ]
