# Generated by Django 4.2.5 on 2023-10-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_ordine_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='elemento_ordine',
        ),
        migrations.AddField(
            model_name='ordine',
            name='elemento_ordine',
            field=models.ManyToManyField(to='polls.elementoordine'),
        ),
    ]
