# Generated by Django 4.2.5 on 2023-10-20 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_remove_ordine_elemento_ordine_ordine_elemento_ordine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='elemento_ordine',
        ),
        migrations.AddField(
            model_name='ordine',
            name='elemento_ordine',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='polls.elementoordine'),
        ),
    ]
