# Generated by Django 4.2.5 on 2023-10-20 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0011_remove_ordine_elemento_ordine_ordine_elemento_ordine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordine',
            name='elemento_ordine',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.elementoordine'),
        ),
        migrations.AlterField(
            model_name='ordine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
